import type { SocCase } from '../types'
import {
  closureStatusLabels,
  confidenceLabels,
  entityTypeLabels,
  evidenceTypeLabels,
  findingCategoryLabels,
  findingStatusLabels,
  priorityLabels,
  questionStatusLabels,
  severityLabels,
  sourceLabels,
  statusLabels,
  verdictLabels,
} from '../data/labels'
import { formatDateTime } from './format'

/**
 * Turns a SocCase into a clean Markdown investigation report. Pure, read-only,
 * dependency-free, synthetic data only.
 */

type TitleMap = Map<string, string>

const FALLBACK_GAPS = [
  'Full email headers still needed',
  'Decoded payload still needed',
  'Endpoint script-block logs still needed',
  'DNS / proxy follow-up still needed',
  'Containment confirmation still needed',
]

const isString = (value: string | undefined): value is string => Boolean(value)

function titlesFor(ids: string[] | undefined, map: TitleMap): string[] {
  return (ids ?? []).map((id) => map.get(id)).filter(isString)
}

export function buildCaseReport(socCase: SocCase): string {
  const evidenceTitle: TitleMap = new Map(socCase.evidence.map((item) => [item.id, item.title]))
  const timelineTitle: TitleMap = new Map(socCase.timeline.map((event) => [event.id, event.title]))
  const findingTitle: TitleMap = new Map(socCase.findings.map((finding) => [finding.id, finding.title]))

  const sections: string[] = [
    `# SOC Investigation Report — ${socCase.title}`,
    caseMetadata(socCase),
    `## Executive summary\n\n${socCase.summary || '_No summary provided._'}`,
    statusAndClassification(socCase),
    affectedEntities(socCase),
    evidenceSummary(socCase),
    timeline(socCase, evidenceTitle),
    decisionJournal(socCase),
    findings(socCase, evidenceTitle, timelineTitle),
    mitreMapping(socCase, findingTitle, evidenceTitle),
    recommendations(socCase),
    closureRationale(socCase),
    missingEvidence(socCase),
    '## Synthetic data disclaimer\n\n_This report was generated by SOC Case Workspace, an educational portfolio tool. All data is synthetic — this is not a real security incident._',
  ]

  return `${sections.join('\n\n')}\n`
}

/** Safe download filename based on the case title and today's date. */
export function reportFilename(socCase: SocCase): string {
  const slug =
    socCase.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '')
      .slice(0, 60) || 'case'
  const date = new Date().toISOString().slice(0, 10)
  return `soc-report-${slug}-${date}.md`
}

function caseMetadata(socCase: SocCase): string {
  return [
    '## Case metadata',
    '',
    `- **Case ID:** ${socCase.id}`,
    `- **Severity:** ${severityLabels[socCase.severity]}`,
    `- **Status:** ${statusLabels[socCase.status]}`,
    `- **Source:** ${sourceLabels[socCase.source]}${socCase.sourceDetail ? ` (${socCase.sourceDetail})` : ''}`,
    `- **Owner:** ${socCase.owner}`,
    `- **Created:** ${formatDateTime(socCase.createdAt)}`,
    `- **Updated:** ${formatDateTime(socCase.updatedAt)}`,
  ].join('\n')
}

function statusAndClassification(socCase: SocCase): string {
  const closure = socCase.closure
  return [
    '## Case status and classification',
    '',
    `- **Workflow status:** ${statusLabels[socCase.status]}`,
    `- **Classification:** ${closure?.verdict ? verdictLabels[closure.verdict] : '_Not set_'}`,
    `- **Closure status:** ${closure?.closureStatus ? closureStatusLabels[closure.closureStatus] : '_Not set_'}`,
  ].join('\n')
}

function affectedEntities(socCase: SocCase): string {
  const head = '## Affected entities'
  if (socCase.affectedEntities.length === 0) return `${head}\n\n_None recorded._`
  const rows = socCase.affectedEntities.map(
    (entity) =>
      `- **${entityTypeLabels[entity.type]}:** \`${entity.value}\`${entity.role ? ` — ${entity.role}` : ''}`,
  )
  return `${head}\n\n${rows.join('\n')}`
}

function evidenceSummary(socCase: SocCase): string {
  const head = '## Evidence summary'
  if (socCase.evidence.length === 0) return `${head}\n\n_None recorded._`
  const blocks = socCase.evidence.map((item) => {
    const meta = [
      evidenceTypeLabels[item.type],
      item.source,
      item.observedAt && formatDateTime(item.observedAt),
    ]
      .filter(Boolean)
      .join(' · ')
    const lines = [`- **${item.title}** (${meta})`, `  - ${item.detail}`]
    if (item.analystNote) lines.push(`  - _Note: ${item.analystNote}_`)
    return lines.join('\n')
  })
  return `${head}\n\n${blocks.join('\n')}`
}

function timeline(socCase: SocCase, evidenceTitle: TitleMap): string {
  const head = '## Timeline'
  if (socCase.timeline.length === 0) return `${head}\n\n_None recorded._`
  const sorted = [...socCase.timeline].sort((a, b) => a.timestamp.localeCompare(b.timestamp))
  const rows = sorted.map((event) => {
    const evidence = titlesFor(event.relatedEvidenceIds, evidenceTitle)
    const suffix = evidence.length ? ` _(evidence: ${evidence.join(', ')})_` : ''
    return `- **${formatDateTime(event.timestamp)}** — **${event.title}**: ${event.description}${suffix}`
  })
  return `${head}\n\n${rows.join('\n')}`
}

function decisionJournal(socCase: SocCase): string {
  const head = '## Analyst questions / decision journal'
  if (socCase.analystQuestions.length === 0) return `${head}\n\n_None recorded._`
  const blocks = socCase.analystQuestions.map((question) => {
    const lines = [`- **${question.question}** — _${questionStatusLabels[question.status]}_`]
    if (question.answer) lines.push(`  - Answer: ${question.answer}`)
    if (question.rationale) lines.push(`  - Rationale: ${question.rationale}`)
    return lines.join('\n')
  })
  return `${head}\n\n${blocks.join('\n')}`
}

function findings(socCase: SocCase, evidenceTitle: TitleMap, timelineTitle: TitleMap): string {
  const head = '## Findings'
  if (socCase.findings.length === 0) return `${head}\n\n_None recorded._`
  const blocks = socCase.findings.map((finding) => {
    const tags = [
      finding.category && findingCategoryLabels[finding.category],
      finding.severity && `${severityLabels[finding.severity]} severity`,
      `${confidenceLabels[finding.confidence]} confidence`,
      finding.status && findingStatusLabels[finding.status],
    ]
      .filter(Boolean)
      .join(' · ')
    const lines = [`### ${finding.title}`, `_${tags}_`, '', finding.description]
    const evidence = titlesFor(finding.relatedEvidenceIds, evidenceTitle)
    if (evidence.length) lines.push('', `**Supporting evidence:** ${evidence.join(', ')}`)
    const events = titlesFor(finding.relatedTimelineEventIds, timelineTitle)
    if (events.length) lines.push(`**Related timeline:** ${events.join(', ')}`)
    return lines.join('\n')
  })
  return `${head}\n\n${blocks.join('\n\n')}`
}

function mitreMapping(socCase: SocCase, findingTitle: TitleMap, evidenceTitle: TitleMap): string {
  const head = '## MITRE ATT&CK mapping'
  if (socCase.mitreMappings.length === 0) return `${head}\n\n_None recorded._`
  const blocks = socCase.mitreMappings.map((mapping) => {
    const meta = `${mapping.tactic ? `${mapping.tactic} · ` : ''}${confidenceLabels[mapping.confidence]} confidence`
    const lines = [`### ${mapping.techniqueId} — ${mapping.techniqueName}`, `_${meta}_`]
    if (mapping.rationale) lines.push('', `**Rationale:** ${mapping.rationale}`)
    const supportingFindings = titlesFor(mapping.relatedFindingIds, findingTitle)
    if (supportingFindings.length) lines.push(`**Supporting findings:** ${supportingFindings.join(', ')}`)
    const evidence = titlesFor(mapping.relatedEvidenceIds, evidenceTitle)
    if (evidence.length) lines.push(`**Supporting evidence:** ${evidence.join(', ')}`)
    return lines.join('\n')
  })
  return `${head}\n\n${blocks.join('\n\n')}`
}

function recommendations(socCase: SocCase): string {
  const head = '## Recommendations / next actions'
  if (socCase.recommendations.length === 0) return `${head}\n\n_None recorded._`
  const rows = socCase.recommendations.map(
    (rec) => `- **${rec.title}** (${priorityLabels[rec.priority]} priority): ${rec.description}`,
  )
  return `${head}\n\n${rows.join('\n')}`
}

function closureRationale(socCase: SocCase): string {
  const head = '## Closure rationale'
  const closure = socCase.closure
  if (!closure || (!closure.rationale && !closure.recommendedAction && !closure.impactSummary)) {
    return `${head}\n\n_Not provided._`
  }
  const lines: string[] = []
  if (closure.rationale) lines.push(`**Rationale:** ${closure.rationale}`)
  if (closure.recommendedAction) lines.push(`**Recommended action:** ${closure.recommendedAction}`)
  if (closure.impactSummary) lines.push(`**Impact:** ${closure.impactSummary}`)
  if (closure.closedAt) {
    lines.push(`**Closed:** ${formatDateTime(closure.closedAt)}${closure.closedBy ? ` by ${closure.closedBy}` : ''}`)
  }
  return `${head}\n\n${lines.join('\n\n')}`
}

function missingEvidence(socCase: SocCase): string {
  const head = '## Limitations / missing evidence'
  const open = socCase.analystQuestions
    .filter((question) => question.status === 'open')
    .map((question) => question.question)
  const gaps = open.length ? open : FALLBACK_GAPS
  const note = open.length
    ? 'Open analyst questions / investigation gaps:'
    : 'No open questions recorded; common follow-ups for this case type:'
  return `${head}\n\n${note}\n\n${gaps.map((gap) => `- ${gap}`).join('\n')}`
}
