import type { SocCase } from '../types'
import {
  closureStatusLabels,
  confidenceLabels,
  entityTypeLabels,
  evidenceTypeLabels,
  findingCategoryLabels,
  findingStatusLabels,
  labDisclosureStateLabels,
  labWriteupStatusLabels,
  priorityLabels,
  questionStatusLabels,
  recommendationCategoryLabels,
  recommendationStatusLabels,
  severityLabels,
  sourceLabels,
  statusLabels,
  verdictLabels,
} from '../data/labels'
import { formatDateTime } from './format'
import { reviewCaseQuality } from './caseQuality'

/**
 * Turns a SocCase into a clean Markdown investigation report. Pure, read-only,
 * dependency-free, synthetic data only.
 */

type TitleMap = Map<string, string>

const isString = (value: string | null | undefined): value is string => Boolean(value)

function titlesFor(ids: string[] | undefined, map: TitleMap): string[] {
  return (ids ?? []).map((id) => map.get(id)).filter(isString)
}

export function buildCaseReport(socCase: SocCase): string {
  const evidenceTitle: TitleMap = new Map(socCase.evidence.map((item) => [item.id, item.title]))
  const timelineTitle: TitleMap = new Map(socCase.timeline.map((event) => [event.id, event.title]))
  const findingTitle: TitleMap = new Map(socCase.findings.map((finding) => [finding.id, finding.title]))

  const sections: Array<string | null> = [
    `# SOC Investigation Report: ${socCase.title}`,
    `## Executive summary\n\n${socCase.summary || '_No executive summary has been recorded for this case._'}`,
    caseMetadata(socCase),
    statusAndClassification(socCase),
    affectedEntities(socCase),
    evidenceSummary(socCase),
    timeline(socCase, evidenceTitle),
    findings(socCase, evidenceTitle, timelineTitle),
    mitreMapping(socCase, findingTitle, evidenceTitle),
    decisionJournal(socCase),
    closureRationale(socCase),
    recommendations(socCase),
    missingEvidence(socCase),
    caseQualityLimitations(socCase),
    labTrainingContext(socCase),
    '## Educational use and synthetic-data disclaimer\n\n_This report was generated by SOC Case Workspace, an educational portfolio tool. All data is synthetic and sanitized for learning; this is not a real security incident._',
  ]

  return `${sections.filter(isString).join('\n\n')}\n`
}

/** Safe download filename based on the case title and today's date. */
export function reportFilename(socCase: SocCase): string {
  const slug =
    socCase.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '')
      .slice(0, 60) || 'case'
  const date = new Date().toISOString().slice(0, 10)
  return `soc-report-${slug}-${date}.md`
}

function caseMetadata(socCase: SocCase): string {
  return [
    '## Case metadata',
    '',
    `- **Case ID:** ${socCase.id}`,
    `- **Severity:** ${severityLabels[socCase.severity]}`,
    `- **Status:** ${statusLabels[socCase.status]}`,
    `- **Source:** ${sourceLabels[socCase.source]}${socCase.sourceDetail ? ` (${socCase.sourceDetail})` : ''}`,
    `- **Owner:** ${socCase.owner}`,
    `- **Created:** ${formatDateTime(socCase.createdAt)}`,
    `- **Updated:** ${formatDateTime(socCase.updatedAt)}`,
  ].join('\n')
}

function statusAndClassification(socCase: SocCase): string {
  const closure = socCase.closure
  return [
    '## Assessment and disposition',
    '',
    `- **Workflow status:** ${statusLabels[socCase.status]}`,
    `- **Classification:** ${closure?.verdict ? verdictLabels[closure.verdict] : '_Not set_'}`,
    `- **Closure status:** ${closure?.closureStatus ? closureStatusLabels[closure.closureStatus] : '_Not set_'}`,
    `- **Security / business impact:** ${closure?.impactSummary || '_Not recorded_'}`,
  ].join('\n')
}

function labTrainingContext(socCase: SocCase): string | null {
  const head = '## Lab / training context'
  const lab = socCase.lab
  if (!lab?.enabled) return null
  const lines = [
    `- **Platform:** ${lab.platform || '_Not set_'}`,
    `- **Lab name:** ${lab.labName || '_Not set_'}`,
    `- **Writeup status:** ${labWriteupStatusLabels[lab.writeupStatus ?? 'not_started']}`,
    `- **Public writeup allowed:** ${labDisclosureStateLabels[lab.publicWriteupAllowed ?? 'unknown']}`,
    `- **Spoiler-sensitive:** ${labDisclosureStateLabels[lab.spoilerSensitive ?? 'unknown']}`,
  ]
  if (lab.scenarioSummary) lines.push(`- **Scenario summary:** ${lab.scenarioSummary}`)
  if (lab.toolsUsed) lines.push(`- **Tools used:** ${lab.toolsUsed}`)
  if (lab.learningNotes) lines.push(`- **Learning notes:** ${lab.learningNotes}`)
  lines.push(
    '- **Lab disclaimer:** Use this section for sanctioned training only. Do not publish restricted answers, copyrighted lab material, or spoiler-sensitive content without permission.',
  )
  return `${head}\n\n${lines.join('\n')}`
}

function affectedEntities(socCase: SocCase): string {
  const head = '## Affected entities'
  if (socCase.affectedEntities.length === 0) return `${head}\n\n_No affected entities have been recorded._`
  const rows = socCase.affectedEntities.map((entity) => {
    const context = [entity.role, entity.description].filter(Boolean).join(' — ')
    return `- **${entityTypeLabels[entity.type]}:** \`${entity.value}\`${context ? ` — ${context}` : ''}`
  })
  return `${head}\n\n${rows.join('\n')}`
}

function evidenceSummary(socCase: SocCase): string {
  const head = '## Evidence reviewed'
  if (socCase.evidence.length === 0) return `${head}\n\n_No evidence has been recorded._`
  const intro =
    'Evidence is listed as observed artifacts and analyst notes. Findings below should be traceable back to these records.'
  const blocks = socCase.evidence.map((item) => {
    const meta = [
      evidenceTypeLabels[item.type],
      item.source,
      item.observedAt && formatDateTime(item.observedAt),
    ]
      .filter(Boolean)
      .join(' · ')
    const lines = [`- **${item.title}** (${meta})`, `  - ${item.detail}`]
    if (item.analystNote) lines.push(`  - _Note: ${item.analystNote}_`)
    return lines.join('\n')
  })
  return `${head}\n\n${intro}\n\n${blocks.join('\n')}`
}

function timeline(socCase: SocCase, evidenceTitle: TitleMap): string {
  const head = '## Timeline of activity'
  if (socCase.timeline.length === 0) return `${head}\n\n_No timeline events have been recorded._`
  const sorted = [...socCase.timeline].sort((a, b) => a.timestamp.localeCompare(b.timestamp))
  const rows = sorted.map((event) => {
    const evidence = titlesFor(event.relatedEvidenceIds, evidenceTitle)
    const suffix = evidence.length ? ` _(evidence: ${evidence.join(', ')})_` : ''
    return `- **${formatDateTime(event.timestamp)}** — **${event.title}**: ${event.description}${suffix}`
  })
  return `${head}\n\n${rows.join('\n')}`
}

function decisionJournal(socCase: SocCase): string {
  const head = '## Analyst reasoning and decision journal'
  if (socCase.analystQuestions.length === 0) return `${head}\n\n_No analyst questions or decisions have been recorded._`
  const ordered = [...socCase.analystQuestions].sort((a, b) => {
    if (a.status === b.status) return a.createdAt.localeCompare(b.createdAt)
    if (a.status === 'open') return -1
    if (b.status === 'open') return 1
    return a.createdAt.localeCompare(b.createdAt)
  })
  const blocks = ordered.map((question) => {
    const lines = [`- **${question.question}** — _${questionStatusLabels[question.status]}_`]
    if (question.answer) lines.push(`  - Answer: ${question.answer}`)
    if (question.rationale) lines.push(`  - Rationale: ${question.rationale}`)
    return lines.join('\n')
  })
  return `${head}\n\n${blocks.join('\n')}`
}

function findings(socCase: SocCase, evidenceTitle: TitleMap, timelineTitle: TitleMap): string {
  const head = '## Findings'
  if (socCase.findings.length === 0) return `${head}\n\n_No analytical findings have been recorded._`
  const blocks = socCase.findings.map((finding) => {
    const tags = [
      finding.category && findingCategoryLabels[finding.category],
      finding.severity && `${severityLabels[finding.severity]} severity`,
      `${confidenceLabels[finding.confidence]} confidence`,
      finding.status && findingStatusLabels[finding.status],
    ]
      .filter(Boolean)
      .join(' · ')
    const lines = [`### ${finding.title}`, `_${tags}_`, '', finding.description]
    const evidence = titlesFor(finding.relatedEvidenceIds, evidenceTitle)
    if (evidence.length) lines.push('', `**Supporting evidence:** ${evidence.join(', ')}`)
    else if (finding.status !== 'rejected') lines.push('', '**Supporting evidence:** _No evidence linked._')
    const events = titlesFor(finding.relatedTimelineEventIds, timelineTitle)
    if (events.length) lines.push(`**Related timeline:** ${events.join(', ')}`)
    return lines.join('\n')
  })
  return `${head}\n\n${blocks.join('\n\n')}`
}

function mitreMapping(socCase: SocCase, findingTitle: TitleMap, evidenceTitle: TitleMap): string {
  const head = '## MITRE ATT&CK assessment'
  if (socCase.mitreMappings.length === 0) return `${head}\n\n_No analyst-authored ATT&CK mappings have been recorded._`
  const blocks = socCase.mitreMappings.map((mapping) => {
    const meta = `${mapping.tactic ? `${mapping.tactic} · ` : ''}${confidenceLabels[mapping.confidence]} confidence`
    const lines = [`### ${mapping.techniqueId} — ${mapping.techniqueName}`, `_${meta}_`]
    if (mapping.rationale) lines.push('', `**Rationale:** ${mapping.rationale}`)
    else lines.push('', '**Rationale:** _No analyst rationale recorded._')
    const supportingFindings = titlesFor(mapping.relatedFindingIds, findingTitle)
    if (supportingFindings.length) lines.push(`**Supporting findings:** ${supportingFindings.join(', ')}`)
    const evidence = titlesFor(mapping.relatedEvidenceIds, evidenceTitle)
    if (evidence.length) lines.push(`**Supporting evidence:** ${evidence.join(', ')}`)
    return lines.join('\n')
  })
  return `${head}\n\n${blocks.join('\n\n')}`
}

function recommendations(socCase: SocCase): string {
  const head = '## Response recommendations and next actions'
  if (socCase.recommendations.length === 0) return `${head}\n\n_No response recommendations have been recorded._`
  const rows = socCase.recommendations.map((rec) => {
    const metadata = [
      rec.category && recommendationCategoryLabels[rec.category],
      `${priorityLabels[rec.priority]} priority`,
      rec.status && recommendationStatusLabels[rec.status],
    ].filter(Boolean).join(' · ')
    return `- **${rec.title}** (${metadata})${rec.description ? `: ${rec.description}` : ''}`
  })
  return `${head}\n\n${rows.join('\n')}`
}

function closureRationale(socCase: SocCase): string {
  const head = '## Closure assessment'
  const closure = socCase.closure
  if (!closure || (!closure.rationale && !closure.recommendedAction && !closure.impactSummary)) {
    return `${head}\n\n_No closure rationale, impact summary, or next action has been recorded._`
  }
  const lines: string[] = []
  lines.push(
    'Closure should explain what happened, what supports the conclusion, what remains uncertain, and what should happen next.',
  )
  if (closure.rationale) lines.push(`**Rationale:** ${closure.rationale}`)
  if (closure.recommendedAction) lines.push(`**Recommended action:** ${closure.recommendedAction}`)
  if (closure.impactSummary) lines.push(`**Impact:** ${closure.impactSummary}`)
  if (closure.closedAt) {
    lines.push(`**Closed:** ${formatDateTime(closure.closedAt)}${closure.closedBy ? ` by ${closure.closedBy}` : ''}`)
  }
  return `${head}\n\n${lines.join('\n\n')}`
}

function caseQualityLimitations(socCase: SocCase): string {
  const head = '## Case quality and review notes'
  const review = reviewCaseQuality(socCase)
  const lines = [
    '_Advisory review only: this section helps a human reviewer spot weak evidence, unresolved questions, and report-readiness gaps. It does not block export._',
    '',
    `- **Completion:** ${review.completion.complete} / ${review.completion.total} checks complete (${review.completion.label})`,
    `- **Needs attention:** ${review.counts.warning}`,
    `- **Missing:** ${review.counts.missing}`,
  ]
  if (review.coachSuggestions.length > 0) {
    lines.push('', 'Reviewer notes:')
    lines.push(...review.coachSuggestions.map((suggestion) => `- ${suggestion}`))
  } else {
    lines.push('', '_No major quality gaps were flagged by the advisory review._')
  }
  return `${head}\n\n${lines.join('\n')}`
}

function missingEvidence(socCase: SocCase): string {
  const head = '## Investigation limitations and open questions'
  const open = socCase.analystQuestions
    .filter((question) => question.status === 'open')
    .map((question) => question.question)
  if (open.length === 0) {
    return `${head}\n\n_No open analyst questions are currently recorded. The analyst should still validate whether evidence gaps, data-source limits, or business-context uncertainty remain before final closure._`
  }
  return `${head}\n\nThe following analyst questions remain unresolved and should be addressed or explicitly accepted as limitations before relying on the report as final:\n\n${open.map((gap) => `- ${gap}`).join('\n')}`
}
